name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
      - uses: cachix/cachix-action@v12
        with:
          name: each-commit-green
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix develop --command devenv ci
      - run: nix develop --command devenv shell echo ok
      - run: nix build .#
